# Change these first
owner: katharostech # Your GitHub username
repo: uptime-monitor # Your Github repository name

# Add your sites here
sites:
  - name: KatharosTech.com
    url: https://katharostech.com
assignees:
  - zicklag

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.katharostech.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://katharostech.com/statics/logo.svg
  name: KatharosTech Site Status
  introTitle: Realtime status of Katharos Technology's websites
  introMessage: >
    This is a realtime dashboard displaying the status of Katharos Technolgy's websites,
    monitored on [GitHub](https://github.com/katharostech/uptime-monitor). This status
    page is powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
notifications:
  - type: email
  
workflowSchedule:
  uptime: "0 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
